spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa.hibernate:
    ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

debug: true

server:
  port: 8080