# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  greeting_job:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: revfactory/olive-notice@main
        with:
          who-to-greet: 'KAKAO~!!'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
